# Generated by Django 6.0 on 2025-12-19 23:32

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('slug', models.SlugField(unique_for_date='publish')),
                ('content', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UPLOADED', 'UPLOADED')], default='DRAFT')),
                ('category', models.CharField(choices=[('STUDY NOTES', 'STUDY NOTES'), ('LEARNIGN RESOURCES', 'LEARNIGN RESOURCES'), ('SHORT EXPLANATIONS', 'SHORT EXPLANATIONS'), ('IDEAS', 'IDEAS')], default='STUDY NOTES')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published',),
            },
            managers=[
                ('uploaded', django.db.models.manager.Manager()),
                ("draft", django.db.models.manager.Manager()),
            ],
        ),
    ]
