# Generated by Django 6.0 on 2025-12-19 23:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entrymodel',
            managers=[
                ('uploaded', django.db.models.manager.Manager()),
            ],
        ),
    ]
