# Generated by Django 6.0 on 2025-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_entrymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
