# Generated by Django 6.0 on 2025-12-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_entrymodel_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entrymodel',
            managers=[
            ],
        ),
    ]
